spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myticket
    username: postgres
    password: qwertyuiop
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    username: sipoufoknj@gmail.com
    password: hxdd gjcd fieq zppr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

ticket:
  app:
    jwtSecret: MyT!cket@2023:)
    jwtExpirationMs: 86400000

frontEnd:
  url: http://51.178.136.89:3000/
  admin:
    url: http://51.178.136.89:3200/
